### ISSUE TITLE
Redesign Project Settings

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#1176]
The Project Settings page is unwieldy.

Use the tabs of #2415, with appropriate groupings
- [x] Convert project switch into a separate dropdown selector (#2416)
- [ ] Tabs for project... (#2569)
  - Basic (Name/Archive/Autocomplete)
  - Languages
  - Users
  - Import/Export
  - Schedule 
- [ ] ~~Could merge BaseSettings, ProjectSettings, SiteSettings into a single Settings folder with common components (and things specific to ProjectSettings and SiteSettings in respective subfolders)~~ Move ProjectUsers out from ProjectSettings, since its contents are used by both ProjectsSettings and SiteSettings (#2569)
