### ISSUE TITLE
Some Backend files have no unit test coverage

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#2647]
- [x] Backend/Controllers/InviteController.cs (#2663)
- [x] Backend/Controllers/StatisticsController.cs (#2669)
- [x] Backend/Services/EmailService.cs (#2671)
- [x] Backend/Services/InviteService.cs (#2672)
