### ISSUE TITLE
Create Docker-based Deployment

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#427]
Follow on of #414.

This issue is to collect the work that needs to be done to deploy to a production server. The existing deployment process should be able to be greatly simplified now that Docker has been delegated much of the application installation and configuration process.

### Tasks that need to be done

> This list is a work-in-progress

- [ ] Install Docker on the target if not already installed.
  - https://docs.docker.com/engine/install/ubuntu/
- [ ] Download TheCombine source project
  - Option one
    - Install Git
    - `git clone https://github.com/sillsdev/TheCombine.git`
  - Option two
    - `curl https://github.com/sillsdev/TheCombine/archive/master.zip master.zip`
    - Extract
- [ ] Generate/configure `.env.web`
  - [ ] Generate a secure, random `ASPNETCORE_JWT_SECRET_KEY`
- [ ] Generate [`production.yml` overlay](https://docs.docker.com/compose/production/#modify-your-compose-file-for-production) with `nginx.build.args` (Example added in #446)
  - [ ] Disable `CAPTCHA_REQUIRED` if needed
  - [ ] Generate a new `CAPTCHA_SITE`?
- [ ] Generate/pull in SSL certificates from Lets Encrypt
  - [ ] [Install SSL certificates into Docker Container](https://github.com/sillsdev/TheCombine/blob/01aaeb8c6c920b0bdcd561e33dccd686f14804b9/README.md#ssl-certificates)
- [ ] `docker compose up --build -d`

All persistant data (Mongo database, SSL certs) will be stored in persistent Docker volumes associated with the Docker Compose project.

**Comment by jmgrady** [comment]
A couple of comments/questions:

1. Don't you mean install docker on the target?  Both host & target?  Ansible is a good option for installing on the target.
2. Regarding downloading the source - what about using a tag/branch specifier - tags for released builds, branches for testing.  `curl` is probably better than `git` so that we don't have the entire repo.
3. .env.web should be for the backend, correct?  Not the web (nginx) container.  Maybe I read that wrong.  The current deployment sets ASPNETCORE_JWT_SECRET_KEY as an environment variable for the backend service.
4. Regarding docker-compose-prod.yml, Ansible has a docker-compose module.  The yaml for docker compose is almost identical to the Ansible yaml for the docker-compose module.  The advantage of using Ansible for the production targets is that it can setup everything else, such as installing docker, setting up certificates, etc.  The problem we need to address with using Ansible is how to make it easy for developers without having to manage two different docker files.  (Ansible will let us parameterize some of the docker compose yaml based on the target so that might help).  Let's talk about this.

**Comment by jmgrady** [comment]
@johnthagen I saw that you are using nginx:stable-alpine.  This might be useful to us as well: https://wiki.alpinelinux.org/wiki/Nginx_as_reverse_proxy_with_acme_(letsencrypt)
In general, it means a 2-step approach to setting up the web server (the same is true for apache).  We need to have a web server listening on port 80 to create or renew the certificate.  Once we have the certificate, we can configure the server for https.

I setup the certificate for our current public server using certbot.  With certbot you can use _standalone_ mode to create the certificate (i.e., no web server yet) and then setup the web server.  The problem is that you need to either convert the renewal to use _webroot_ mode or setup pro/post renewal hooks to stop the web server while the certificate is renewed.  We expect this to be once every 30 days at 3:00 am (in OUR time zone but the public server can be accessed from anywhere).  There is more info on certbot at https://certbot.eff.org/ and https://pkgs.alpinelinux.org/package/edge/community/x86/certbot

**Comment by johnthagen** [comment]
> Don't you mean install docker on the target? Both host & target? Ansible is a good option for installing on the target.

Yes, exactly. On the target system being set up that will be running TheCombine. I updated the text to try to make it a little more clear.

> Regarding downloading the source - what about using a tag/branch specifier - tags for released builds, branches for testing. curl is probably better than git so that we don't have the entire repo.

Yes, I think we should discuss with @jasonleenaylor about having some kind of release process (tagging the repo, keeping a changelog, possibly performing some level of smoke testing at a system level). I agree `curl` would be best (no need to pull the history) and `curl`ing an actual release would be ideal.

> The docker-compose.yml has the backend listed as the web service. But the backend does not really generate any web pages, per se. That is done by the frontend - the service listed as nginx. I think it would be clearer to name these services backend and frontend respectively.

I was following a pretty standard convention I've seen where the backend service is called `web`. I've seen this on several tutorials, so I think it's an okay convention to follow. The same is calling the database service the `db` service.

>  Also, the backend lists /root/.CombineFiles as the backend_data. In the deployment scripts we also had setup /var/thecombine/uploads for the audio file uploads (last summer). I think that it would be good to have a single location for this type of stuff, either /var/thecombine or ~/.CombineFiles.
3.5 (later addition ;-) )

Yeah, we need to audit all of the locations files can go if it's not just `~/.CombineFiles`. We'll need a volume for each location if there is more than one to persist the data. If you're able to come up with a comprehensive list (with references to the backend source code) that'd be great.

> Currently we do not run the backend as root to limit its ability to affect other processes on the server. This is obviated by putting it in a container, correct?

Yes, this is a nice benefit of the container. There is some motivation to try to get the backend to run as a non-root user because if the backend is exploited then it will have root privileges on the machine. This can be a follow on issue we investigate.

> Regarding docker-compose-prod.yml, Ansible has a docker-compose module. The yaml for docker compose is almost identical to the Ansible yaml for the docker-compose module. The advantage of using Ansible for the production targets is that it can setup everything else, such as installing docker, setting up certificates, etc. The problem we need to address with using Ansible is how to make it easy for developers without having to manage two different docker files. (Ansible will let us parameterize some of the docker compose yaml based on the target so that might help). Let's talk about this.

Yeah, let's talk about this. I think having Ansible generate a thin config over top of the base configuration would be a good way to try: https://docs.docker.com/compose/production/#modify-your-compose-file-for-production

**Comment by jmgrady** [comment]
@johnthagen Regarding `/var/thecombine/uploads`, I cannot find any reference to that path in the code - only in the Ansible scripts that create it.  (and the directory is just created, there are no environment variables set, etc.)

**Comment by jmgrady** [comment]
Closed by PR #550 Docker Deploy.
