### ISSUE TITLE
Gloss auto suggestions are lacking

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/TheCombine#487]
Improvements needed: 
- [ ] Enhance suggestion algorithm; should suggest longer real words when currently typed text is recognized as a word, word length of suggest words should be increased :
  - #2355 suggests words up to 2 characters longer (though usually just 1); more than that would require a different tool than `nspell` (possibly https://www.npmjs.com/package/typeahead-standalone)
  - Resolved by #2842
- [x] Add dictionaries for all UI languages : #2355 adds what's available in https://cgit.freedesktop.org/libreoffice/dictionaries that isn't too large (so left off ar, pt, ru for now)
- [x] Lazy load the dictionary, load only the one needed for the first analysis language when we load the project : #2355
- [x] Consider splitting dictionary files by first letter, to allow for larger dictionaries (e.g., ar, pt, ru): #2484

**Comment by imnasnainaec** [comment]
Need to allow for multi-word glosses and non-english analysis language.

**Comment by imnasnainaec** [comment]
The ability to load more dictionaries in `nspell` is broken: https://github.com/wooorm/nspell/issues/26
You can add words with `.personal()` but not dictionary files that require interaction with the `.aff`.
Now `nspell` hasn't been updated since Jan '21, so we'll either have to switch to a new spell-checker or switch to raw wordlists.
The latter is probably the way we want to go, even though that requires larger files, since we'll need raw wordlists to add look-ahead suggestions.

**Comment by imnasnainaec** [comment]
`React` example of `typeahead-standalone`: https://github.com/digitalfortress-tech/typeahead-standalone/discussions/67
