### ISSUE TITLE
[ProjectSettings] Update visibility for non-owner users

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#707]
Update the project settings for non-owners to match the following specifications (matching their permissions).

- [x] Project Name:(permission delete edit settings users) (#2336)
- [x] Languages: Read Only (if not permission delete edit settings users) (#2373)
- [x] Import Data: Not Visible (permission import) (#2336)
- [x] Export Project:  (permission export) (#2336)
- [x] Autocomplete:  (permission delete edit settings users) (#2336)
- [x] Current Users:  (permission delete edit settings users) (#2336)
- [x] Add User: (permission delete edit settings users) (#2336)
- [ ] Workshop Schedule: Read Only (if not permission statistics) (#2414)
- [x] Archive Project: (if not permission archive) (#2336)
