### ISSUE TITLE
[ProjectSettings] Project admin should be able to update user roles.

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#940]
Currently, the project creator/owner is the only project admin, and only *site* admins can remove users from a project.

A project admin should be able to:
- [x] Remove (non-admin) users (solved in #1253)

Before allowing more than one admin on a project, we need:
- [x] A project owner permission distinct from project admin (solved in #1257)
- [x] A database update to apply the new permission to each projects singular admin (solved in #1257)

A project owner should be able to
- [x] Add/Remove project admin status to/from another user (solved in #1253)
- ~Transfer ownership to a different admin~ (moved to #1270)
- ~Archive/restore the project~ (moved to #1270)

Related: #705, #708
